# Generated by Django 2.1 on 2022-01-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='Quantity',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
