# Generated by Django 2.1 on 2022-01-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='Quantity',
        ),
    ]
